config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get "/clients", to: 'pages#clients'
  resources :users, only: [:show] #totally independent
  resources :wallets do
    resources :offers, only: [:create]
  end

  resources :currencies, only: [:index, :show] do
    post 'refresh', on: :collection
  end
  resources :offers, only: [:show, :index, :destroy] do
    resources :trades, only: [:new, :create, :index, :show]
  end
  get "/my", to: 'offers#my'
  get "/my_trades", to: 'trades#my_trades'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/currency.rb
require "open-uri"
require 'json'

class Currency < ApplicationRecord
  has_many :wallets, dependent: :destroy

  def self.refresh
    url = 'https://api.coinmarketcap.com/v2/ticker/?limit=12'
    read = open(url).read
    hash = JSON.parse(read)

    hash['data'].each do |key, value|

      coin = Currency.find_or_create_by(website_slug: value['website_slug'])

      coin.name = value['name']
      coin.symbol = value['symbol']
      coin.website_slug = value['website_slug']
      coin.rank = value['rank']
      coin.circulating_supply = value['circulating_supply']
      coin.total_supply = value['total_supply']
      coin.max_supply = value['max_supply'].nil? ? 0 : value['max_supply']

      coin.current_price = value['quotes']['USD']['price']
      coin.volume_24h = value['quotes']['USD']['volume_24h']
      coin.market_cap = value['quotes']['USD']['market_cap']
      coin.percent_change_1h = value['quotes']['USD']['percent_change_1h']
      coin.percent_change_24h = value['quotes']['USD']['percent_change_24h']
      coin.percent_change_7d = value['quotes']['USD']['percent_change_7d']
      coin.save
    end

  end

end

app/controllers/currencies_controller.rb
class CurrenciesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show, :refresh]

  def index
    @currencies = policy_scope(Currency)
    @currencies = @currencies.order(id: :asc)
  end

  def show
    @currency = Currency.find(params[:id])
    authorize @currency
  end

  def refresh
    authorize Currency
    Currency.refresh
    redirect_to currencies_path
  end
end

app/views/currencies/index.html.erb
<div class="container">
  <h1>Currencies</h1>
  <h2>Modifications at, every one hour</h2>

  <p><%= link_to 'Refresh', refresh_currencies_path, class: 'btn btn-primary', method: :post %></p>

  <div class="table-responsive">
    <table class="table"> <caption>Optional table caption.</caption>
      <thead>
        <tr>
          <th>#</th>
          <th>Name</th>
          <th>Symbol</th>
          <th>Price</th>
          <th>circulating_supply</th>
          <th>total_supply</th>
          <th>max_supply</th>
          <th>volume_24h</th>
          <th>market_cap</th>
          <th>%change_1h</th>
          <th>%change_24h</th>
          <th>%change_7d</th>
        </tr>
      </thead>
      <tbody>
       <% @currencies.each do |c| %>
        <tr>
          <th scope="rank"><%=c.rank  %>  </th>

        <td> <%= link_to c do %>
          <%= c.name %>
        <% end %>
        </td>
        <td> <%=c.symbol  %> </td>
        <td> <%=number_to_currency(c.current_price, :precision => 2) %> </td>
        <td> <%=number_with_precision(c.circulating_supply, precision:0, delimiter: ",")  %> </td>

        <td> <%=number_with_precision(c.total_supply, precision: 0, delimiter: ",")  %> </td>

        <td> <%= c.max_supply.zero? ? "Not applicable" : number_with_precision(c.max_supply, precision: 0, delimiter: "," )  %> </td>

        <td> <%=number_with_precision(c.volume_24h, precision: 0, delimiter: ",")  %> </td>

        <td> <%=number_to_currency(c.market_cap, :precision => 2 )  %> </td>

        <td> <%=number_to_percentage(c.percent_change_1h, :precision => 2) %></td>

        <td> <%=number_to_percentage(c.percent_change_24h, :precision => 2) %></td>
        <td> <%=number_to_percentage(c.percent_change_7d, :precision => 2)%></td>

      <% end %>
        </tr>

       </tbody>
     </table>

  </div>

</div>

app/views/currencies/show.html.erb
<div class="container">
  <h1 class="text-center"><%= @currency.name %></h1>

  <table class="table">
    <tbody>
      <tr>
        <td>
          Price
        </td>
        <td>
          <%= number_to_currency(@currency.current_price, :precision => 2) %>
        </td>
      </tr>
      <tr>
        <td>
          24h Volume
        </td>
        <td>
          <%= number_with_precision(@currency.volume_24h, precision: 0, delimiter: ",")  %>
        </td>
      </tr>
      <tr>
        <td>
          Circulating Supply
        </td>
        <td>
          <%=number_with_precision(@currency.circulating_supply, precision: 0, delimiter: ",")  %>
        </td>
      </tr>
      <tr>
        <td>
          Maximum Supply
        </td>
        <td>
          <%=number_with_precision(@currency.max_supply, precision: 0, delimiter: ",")  %>
        </td>
      </tr>
    </tbody>
  </table>
  <div class="form-group">
    <label for="sel1">View period</label>
    <select class="form-control" id="period">
      <option value="1D">1 Day</option>
      <option value="1W">1 Week</option>
      <option value="2W">2 Weeks</option>
      <option value="1M">1 Month</option>
      <option value="3M">3 Months</option>
      <option value="6M">6 Months</option>
      <option value="1Y">1 Year</option>
    </select>
  </div>

  <div id="widget-cards" data-currency="<%= @currency.symbol.to_json %>">
    <script id="<%= @currency.symbol %>"></script>
  </div>
  <%= javascript_pack_tag "single_widget" %>

</div>