config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get "/clients", to: 'pages#clients'
  resources :users, only: [:show] #totally independent
  resources :wallets do
    resources :offers, only: [:create]
  end

  resources :currencies, only: [:index, :show] do
    post 'refresh', on: :collection
  end
  resources :offers, only: [:show, :index, :destroy] do
    resources :trades, only: [:new, :create, :index, :show]
  end
  get "/my", to: 'offers#my'
  get "/my_trades", to: 'trades#my_trades'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
 <!-- Logo -->
 <%= link_to root_path, class: "navbar-wagon-brand" do %>
 <%= image_tag "vault.png", height: 50 %>
 <% end %>

 <!-- Right Navigation -->
 <div class="navbar-wagon-right hidden-xs hidden-sm">
   <%= link_to "Currencies", currencies_path, class: "navbar-wagon-item navbar-wagon-link" %>
   <%= link_to "Offers", offers_path, class: "navbar-wagon-item navbar-wagon-link" %>
   <%= link_to "Our Clients", clients_path, class: "navbar-wagon-item navbar-wagon-link" %>

   <% if user_signed_in? %>

   <!-- Links when logged in -->
   <%= link_to "My Wallets", wallets_path  , class: "navbar-wagon-item navbar-wagon-link" %>
   <%= link_to "My Offers", my_path, class: "navbar-wagon-item navbar-wagon-link" %>
   <%= link_to "My Trades", my_trades_path, class: "navbar-wagon-item navbar-wagon-link" %>
   <!-- Avatar with dropdown menu -->
   <div class="navbar-wagon-item">
     <div class="dropdown">
       <%= image_tag "https://images-na.ssl-images-amazon.com/images/I/41-6KxWC-eL.jpg", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
       <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
         <li>
           <%= link_to "#" do %>
           <i class="fas fa-user"></i> <%= t(".profile", default: "Profile") %>
           <% end %>
         </li>
         <li>
           <%= link_to "#" do %>
           <i class="fas fa-cog"></i>  <%= t(".settings", default: "Settings") %>
           <% end %>
         </li>
         <li>
           <%= link_to destroy_user_session_path, method: :delete do %>
           <i class="fas fa-sign-out-alt"></i>  <%= t(".sign_out", default: "Log out") %>
           <% end %>
         </li>
       </ul>
     </div>
   </div>
   <% else %>
   <!-- Login link (when logged out) -->
   <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "btn btn-default" %>
   <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-default" %>
   <% end %>
 </div>

 <!-- Dropdown list appearing on mobile only -->
 <div class="navbar-wagon-item hidden-md hidden-lg">
   <div class="dropdown">
     <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
     <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
      <li><a href="#">Some mobile link</a></li>
      <li><a href="#">Other one</a></li>
      <li><a href="#">Other one</a></li>
    </ul>
  </div>
</div>
</div>