config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get "/clients", to: 'pages#clients'
  resources :users, only: [:show] #totally independent
  resources :wallets do
    resources :offers, only: [:create]
  end

  resources :currencies, only: [:index, :show] do
    post 'refresh', on: :collection
  end
  resources :offers, only: [:show, :index, :destroy] do
    resources :trades, only: [:new, :create, :index, :show]
  end
  get "/my", to: 'offers#my'
  get "/my_trades", to: 'trades#my_trades'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/wallet.rb
class Wallet < ApplicationRecord
  belongs_to :user
  belongs_to :currency

  has_many :offers, dependent: :destroy
  validates_uniqueness_of :currency_id, :scope => :user_id
end

app/controllers/wallets_controller.rb
class WalletsController < ApplicationController
  def index
    @wallets = policy_scope(Wallet.where(user: current_user))
    @currencies = Currency.all
  end

  def show
    @wallet = Wallet.find(params[:id])
    @offer = @wallet.offers.new
    authorize @wallet
  end

  def new
    @wallet = Wallet.new
    @wallet.user = current_user
    authorize @wallet
  end

  def create
    @wallet = Wallet.new(wallet_params)
    @wallet.user = current_user
    authorize @wallet
    if @wallet.save
      redirect_to @wallet
    else
      render :new
    end
  end

  def edit
    @wallet = Wallet.find(params[:id])
    authorize @wallet
  end

  def update
    @wallet = Wallet.find(params[:id])
    authorize @wallet
    @wallet.update(wallet_params)
    redirect_to @wallet
  end

  def destroy
    wallet = Wallet.find(params[:id])
    authorize wallet
    wallet.destroy
    redirect_to wallets_path
  end

  def wallet_params
    params.require(:wallet).permit(:amount, :user_id, :currency_id)
  end
end

app/views/wallets/create.html.erb
<h1>Wallets#create</h1>
<p>Find me in app/views/wallets/create.html.erb</p>

app/views/wallets/destroy.html.erb
<h1>Wallets#destroy</h1>
<p>Find me in app/views/wallets/destroy.html.erb</p>

app/views/wallets/edit.html.erb
<h1> Edit Wallet </h1>
<%= simple_form_for @wallet do |f| %>
    <%= f.input :amount %>
    <%= f.association :currency %>
  <%= f.submit "Edit Wallet", class: "btn btn-primary" %>
  <% end %>

app/views/wallets/index.html.erb
<div class="container">
  <div class="text-center inline-list">
    <h1>My Wallets <i class="fas fa-wallet"></i></h1>

    <h2><%= link_to "Add Wallet", new_wallet_path %></h2>
  </div>

  <div class="container">
    <div class="row">
      <% @wallets.each do |wallet| %>
      <%= link_to wallet do %>
      <div class="col-xs-3">
        <div class="wallet">
          <h4><%= wallet.amount %></h4>
          <h4> <%= wallet.currency.name %></h4>
          <h5>Wallet Value</h5>
          <h5> <%=number_to_currency(wallet.currency.current_price * wallet.amount, precision: 2, delimiter: ',') %></h5>
        </div>
      </div>
      <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/wallets/new.html.erb
<h1> Create Wallet </h1>
<%= simple_form_for @wallet do |f| %>
    <%= f.input :amount %>
    <%= f.association :currency %>
  <%= f.submit "Create Wallet", class: "btn btn-primary" %>
  <% end %>

app/views/wallets/show.html.erb
<div class="container">
  <div class="wallet-show">
    <h1><%= @wallet.amount %> of <%= link_to @wallet.currency do %>
      <%= @wallet.currency.name %></h1>
      <% end %>
      <h2>Market Value (US$) <%= number_to_currency(@wallet.currency.current_price * @wallet.amount, precision: 2, delimiter: ',') %></h2>
    </div>


    <%= simple_form_for([@wallet, @offer]) do |f| %>
    <%= f.input :price %>
    <%= f.input :amount %>
    <%= f.submit %>
    <% end %>

    <%= link_to "Back", wallets_path %>
    <%= link_to "Edit", edit_wallet_path %>
    <%= link_to "Delete?", wallet_path(@wallet),
    method: :delete,
    data: { confirm: "Are you sure?" } %>
  </div>
</div>

app/views/wallets/update.html.erb
<h1>Wallets#update</h1>
<p>Find me in app/views/wallets/update.html.erb</p>