config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get "/clients", to: 'pages#clients'
  resources :users, only: [:show] #totally independent
  resources :wallets do
    resources :offers, only: [:create]
  end

  resources :currencies, only: [:index, :show] do
    post 'refresh', on: :collection
  end
  resources :offers, only: [:show, :index, :destroy] do
    resources :trades, only: [:new, :create, :index, :show]
  end
  get "/my", to: 'offers#my'
  get "/my_trades", to: 'trades#my_trades'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/offer.rb
class Offer < ApplicationRecord
  belongs_to :wallet
  has_one :trade, dependent: :destroy
end
# offers.wallet.currency.name

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    if params[:currency_query].nil?
      @offers = policy_scope(Offer).where(closed: false)
    else
      @offers = policy_scope(Offer)
      @offers = @offers.select do |offer|
        offer.wallet.currency.name.downcase.include?(params[:currency_query].downcase) && offer.closed == false
      end
    end
  end

  def my
    @offers = policy_scope(Offer)
    unless @offers.empty?
      @offers = @offers.select do |offer|
        authorize offer
        offer.wallet.user == current_user
      end
    else
      authorize @offers
    end
  end

  def show
    @offer = Offer.find(params[:id])
    @trade = Trade.new
    @trade.offer = @offer
    # @transaction = @offer.trade.new
    # @transaction.status = "sell"
    authorize @offer
  end

  def create
    @wallet = Wallet.find(params[:wallet_id])
    @offer = Offer.new(offer_params)
    if @offer.amount <= @wallet.amount
      @wallet.amount -= @offer.amount
      @offer.wallet = @wallet
      @offer.user_type = "sell"
      @wallet.save
    end
    authorize @offer
    if @offer.save
      redirect_to @offer
    else
      redirect_to @wallet
    end
  end

  def destroy
    offer = Offer.find(params[:id])
    wallet = Wallet.find(offer.wallet_id)
    wallet.amount += offer.amount
    wallet.save
    authorize offer
    offer.destroy
    redirect_to offers_path
  end

  def offer_params
    params.require(:offer).permit(:user_type, :price, :amount, :wallet_id, :trade_id)
  end
end

app/views/offers/index.html.erb
<div class="container">
  <h1 class="text-center">OFFERS</h1>

  <h2 class="text-center"> TO BUY </h2>
  <div class="row">
    <% @offers.each do |offer| %>
      <%= link_to offer do %>
        <div class="col-xs-3">
          <div class="offer">
            <%= number_with_precision(offer.amount, presicion: 5, significant: true, strip_insignificant_zeros: true, delimiter: ",") %> <%= offer.wallet.currency.name.upcase %>
            <div class="offer-price">
              <%= number_to_currency(offer.price) %>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/offers/my.html.erb
<div class="container">
  <h1 class="text-center">My Offers</h1>
  <div class="row">
    <% @offers.each do |offer| %>
      <%= link_to offer do %>
        <div class="col-xs-3">
          <div class="offer">
            <%= number_with_precision(offer.amount, presicion: 5, significant: true, strip_insignificant_zeros: true, delimiter: ",") %> <%= offer.wallet.currency.name.upcase %>
            <div class="offer-price">
              <%= number_to_currency(offer.price) %>
            </div>
            <div class="offer-price">
              <% if offer.closed %>
                Closed!
              <% else %>
                Open!
              <% end %>
            </div>

          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/offers/show.html.erb
<div class="container">
  <div class="offer-card">
    <h2><i class="fas fa-money-bill-wave"></i> Price: $<%= @offer.price %></h2>
    <h2><i class="fas fa-sort-amount-up"></i> Amount: <%= @offer.amount %></h2>
    <%= link_to @offer.wallet.currency do %>
      <h2><i class="fab fa-bitcoin"></i> Currency: <%= @offer.wallet.currency.name.upcase %></h2>
    <% end %>
    <% if @offer.user_type = "sell" %>
      <%= link_to @offer.wallet.user do %>
        <h2><i class="far fa-user"></i> Seller: <%= @offer.wallet.user.email %></h2>
      <% end %>
    <% end %>

      <%= link_to "Back to Offers", offers_path %>
      <% if @offer.wallet.user != current_user %>
        <%= simple_form_for([@offer, @trade]) do |f| %>
            <%= f.submit %>
        <% end %>
      <% else %>
        <%= link_to "Delete?", offer_path(@offer),
            method: :delete,
            data: { confirm: "Are you sure?" } %>
      <% end %>
  </div>
</div>

app/views/offers/update.html.erb
<h1>Offers#update</h1>
<p>Find me in app/views/offers/update.html.erb</p>